name: cros-build-beerctl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: show rustc version
        run: rustc --version
      
      - name: rustup target add
        run: rustup target add x86_64-unknown-linux-musl
      
      - name: openssl-init
        run: sudo apt-get install libssl-dev
      
      - name: Set OpenSSL directory
        run: export OPENSSL_DIR=/usr/include/openssl
      
      - name: Install pkg-config for musl
        run: sudo apt-get install -y pkg-config-musl

      - name: cross-build
        run: cargo build --release --target x86_64-unknown-linux-musl
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-dir
          path: |
            target/release
      
