name: cros-build-beerctl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: show rustc version
        run: rustc --version
      
      - name: rustup target add
        run: rustup target add x86_64-unknown-linux-musl
      
      - name: openssl-init
        run: sudo apt-get install libssl-dev pkg-config musl-tools
      
#       - name: config openssl
#         run: export OPENSSL_DIR=/usr/local/opt/openssl
      
      - name: config pkg-config
        run: export PKG_CONFIG_SYSROOT_DIR=/
        
#       - name: check openssl
#         run:  ls /usr/local/opt/openssl/

#       - name: check pkg-config
#         run:  ls /usr/local/lib/pkgconfig/

      - name: cross-build
        run: cargo build --release --target x86_64-unknown-linux-musl
      
      - name: show target
        run: ls target
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-dir
          path: |
            target/x86_64-unknown-linux-musl
      
